# Site settings
name: Annabel X. Tan
title: Annabel X. Tan, MPH
description: PhD student @ Dept of Epidemiology and Population Health, Stanford School of Medicine. 
url: https://annabelxtan.github.io/
baseurl: ''
email: annabelxtan@gmail.com
cover: https://annabelxtan.github.io/img/og.png
logo: https://annabelxtan.github.io/img/emojis/technologist.png
resume: https://annabelxtan.github.io/resume.pdf
social:
  - title: email
    url: mailto:annabelxtan@gmail.com
  - title: twitter
    url: https://twitter.com/annabelxt
  - title: instagram
    url: https://instagram.com/annabelxt
  - title: github
    url: https://github.com/annabelxtan
  - title: linkedin
    url: https://www.linkedin.com/in/annabelxtan

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
